### ISSUE TITLE
Config Rarity? 

### ISSUE THREAD

**Issue by louisw22** [Funwayguy/Epic-Siege-Mod#4]
How do you use the configs rarity function? Does zombie apocalypse mode disable other mob spawning??

**Comment by Funwayguy** [comment]
Rarity is basically a 1 in <number> chance of said mobs spawning (It's calculated slightly differently on Ghast/Blaze spawning). Apocalypse mode does disable everything but zombies specifically for those who like playing Minecraft in zombie survival style where even food is scarce because of the lack of animals.
