### ISSUE TITLE
Feature Request: Config option to choose pillaring material

### ISSUE THREAD

**Issue by darchitect7** [Funwayguy/Epic-Siege-Mod#92]
Adore this mod. Can we have an option to pick the pillaring block? I'm using Repose to add gravity to blocks, and cobble is one that I've done that with. Obviously causing problems with mobs trying to use it to get to me. 

And this is a long shot, but there used to be a mod ages ago that had pillaring enemies, but the block they used to pillar disappeared at dawn. Which was awesome because then you didn't have cobble or whatever littering up the landscape. I'm sure that'd take loads longer than just a config option, but I thought I'd mention it anyway.

Thanks for all your awesome mods!

**Comment by Funwayguy** [comment]
Added in 13.162

**Comment by darchitectlp** [comment]
Hey @Funwayguy I've gotten this to work with vanilla blocks, but not with mod blocks. A totally awesome person made me a mod [here](https://www.reddit.com/r/feedthebeast/comments/91e4cv/im_looking_for_a_mod_that_adds_a_block_that/) that has time dependent blocks that disappear... but I can't get the zombies to use them. I also tried to get them to use the flesh block from Thaumcraft (to no avail).

Is this possibly something on your end? I don't want to open a bug report if this is intentional. Thanks again for adding this feature in.

**Comment by Funwayguy** [comment]
*sigh*

Found the issue. Loaded the configs too early before modded block registration events. I'll get a patch out for that soon.

**Comment by darchitectlp** [comment]
> .

Hey... so any chance of a patch for this? I had a super awesome person on reddit make me a mini mod that makes blocks disappear at daytime (or any time, really) but I can't cross test it with ESM until you get it working for modded blocks. I know you do this out of a passion for the game, so no pressure. Just want to check up. Thanks!

 Here's a link to the thread on reddit: [Masa_'s Vanishment Point](https://www.reddit.com/r/feedthebeast/comments/91e4cv/im_looking_for_a_mod_that_adds_a_block_that/)

**Comment by Funwayguy** [comment]
Wait... did I not release the patch for this?

_checks change logs_

Ah damn. I'm really really sorry about that. I had all the code done in my dev environment the day after I sent my last message here and I guess I just forgot I never actually uploaded the build.
